export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const DELETE_TODO = 'DELETE_TODO'

export const LOGIN = 'LOGIN'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'

export const REGISTER = 'REGISTER'
export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_REJECTED = 'REGISTER_REJECTED'
export const REGISTER_FULFILED = 'REGISTER_FULFILED'

export const CROSSWORDLIST = 'CROSSWORDLIST'
export const CROSSWORDLIST_PENDING = 'CROSSWORDLIST_PENDING'
export const CROSSWORDLIST_REJECTED = 'CROSSWORDLIST_REJECTED'
export const CROSSWORDLIST_FULFILED = 'CROSSWORDLIST_FULFILED'

export const ANSWER = "ANSWER"
export const ANSWER_PENDING = "ANSWER_PENDING"
export const ANSWER_REJECTED = "ANSWER_REJECTED"
export const ANSWER_FULFILED = "ANSWER_FULFILED"

export const ANSWER_CEK = "ANSWER_CEK"
export const ANSWER_CEK_PENDING = "ANSWER_CEK_PENDING"
export const ANSWER_CEK_REJECTED = "ANSWER_CEK_REJECTED"
export const ANSWER_CEK_FULFILED = "ANSWER_CEK_FULFILED"

// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
// export const ANSWER = "ANSWER"
